"""Doctor portal RBAC — Sprint 009."""

DOCTOR_PORTAL_READ_ROLES = frozenset({"SUPER_ADMIN", "SYSTEM_ADMIN", "ADMIN", "DOCTOR"})
DOCTOR_PORTAL_WRITE_ROLES = frozenset({"SUPER_ADMIN", "ADMIN", "DOCTOR"})
DOCTOR_PORTAL_NOTE_ROLES = frozenset({"SUPER_ADMIN", "ADMIN", "DOCTOR"})

FORBIDDEN_DOCTOR_RELEASE = frozenset({"RECEPTION", "PATIENT", "LAB_TECHNICIAN"})
