"""Integration platform constants."""

CONNECTOR_TYPES = (
    "LIS", "HIS", "EMR", "PACS", "ANALYZER", "PAYMENT", "INSURANCE",
    "WEBHOOK", "MOBILE", "CUSTOM_API",
)

PROTOCOLS = (
    "REST", "HL7_V2", "FHIR_R4", "ASTM", "DICOM", "SFTP",
    "CSV", "JSON", "XML", "WEBHOOK", "MANUAL",
)

DIRECTIONS = ("INBOUND", "OUTBOUND", "BIDIRECTIONAL")

CONNECTOR_STATUSES = ("DRAFT", "ACTIVE", "PAUSED", "ERROR", "DISABLED")

MESSAGE_TYPES = (
    "PATIENT_CREATE", "PATIENT_UPDATE", "ORDER_CREATE", "ORDER_UPDATE",
    "SAMPLE_COLLECTED", "SAMPLE_RECEIVED", "SAMPLE_REJECTED",
    "RESULT_PRELIMINARY", "RESULT_FINAL", "REPORT_RELEASED",
    "PAYMENT_CREATED", "PAYMENT_CONFIRMED",
    "APPOINTMENT_CREATED", "APPOINTMENT_UPDATED",
)

MESSAGE_STATUSES = (
    "RECEIVED", "VALIDATED", "STAGED", "PROCESSED", "ACKNOWLEDGED",
    "REJECTED", "EXCEPTION", "DUPLICATE", "DEAD_LETTER",
)

TRANSFORMATION_TYPES = (
    "DIRECT", "CONSTANT", "LOOKUP", "DATE_FORMAT", "ENUM_MAP",
    "UNIT_CONVERSION", "CODE_MAPPING", "CUSTOM_SAFE_TRANSFORM",
)

RETRY_STRATEGIES = ("FIXED", "EXPONENTIAL_BACKOFF")

WEBHOOK_EVENTS = (
    "order.created", "order.updated", "sample.collected", "sample.received",
    "result.validated", "report.released", "payment.confirmed",
)

INTEGRATION_PERMISSIONS = (
    "INTEGRATION_VIEW", "INTEGRATION_MANAGE", "CONNECTOR_MANAGE",
    "MAPPING_MANAGE", "MESSAGE_RETRY", "WEBHOOK_MANAGE", "API_CREDENTIAL_MANAGE",
)

RESULT_IMPORT_WORKFLOW = (
    "IMPORTED", "VALIDATION_REQUIRED", "PENDING_REVIEW", "APPROVED", "RELEASED",
)

MAX_PAYLOAD_BYTES = 5 * 1024 * 1024
MAX_RETRIES_DEFAULT = 5
