"""Pilot business engine order and collection status lifecycle."""

ORDER_DRAFT = "draft"
ORDER_PAYMENT_PENDING = "payment_pending"
ORDER_PAID = "paid"
ORDER_SAMPLING = "sampling"
ORDER_COLLECTED = "collected"
ORDER_IN_TRANSIT = "in_transit"
ORDER_LAB_RECEIVED = "lab_received"
ORDER_TESTING = "testing"
ORDER_PENDING_REVIEW = "pending_review"
ORDER_APPROVED = "approved"
ORDER_RELEASED = "released"
ORDER_CANCELLED = "cancelled"

VALID_ORDER_STATUSES = [
    ORDER_DRAFT,
    ORDER_PAYMENT_PENDING,
    ORDER_PAID,
    ORDER_SAMPLING,
    ORDER_COLLECTED,
    ORDER_IN_TRANSIT,
    ORDER_LAB_RECEIVED,
    ORDER_TESTING,
    ORDER_PENDING_REVIEW,
    ORDER_APPROVED,
    ORDER_RELEASED,
    ORDER_CANCELLED,
]

TERMINAL_ORDER_STATUSES = {ORDER_RELEASED, ORDER_CANCELLED}

ORDER_TRANSITIONS: dict[str, list[str]] = {
    ORDER_DRAFT: [ORDER_PAYMENT_PENDING, ORDER_CANCELLED],
    ORDER_PAYMENT_PENDING: [ORDER_PAID, ORDER_CANCELLED],
    ORDER_PAID: [ORDER_SAMPLING, ORDER_CANCELLED],
    ORDER_SAMPLING: [ORDER_COLLECTED, ORDER_CANCELLED],
    ORDER_COLLECTED: [ORDER_IN_TRANSIT],
    ORDER_IN_TRANSIT: [ORDER_LAB_RECEIVED],
    ORDER_LAB_RECEIVED: [ORDER_TESTING],
    ORDER_TESTING: [ORDER_PENDING_REVIEW],
    ORDER_PENDING_REVIEW: [ORDER_APPROVED, ORDER_TESTING],
    ORDER_APPROVED: [ORDER_RELEASED, ORDER_PENDING_REVIEW],
}

COLLECTION_ASSIGNED = "assigned"
COLLECTION_ACCEPTED = "accepted"
COLLECTION_COLLECTED = "collected"
COLLECTION_IN_TRANSIT = "in_transit"
COLLECTION_DELIVERED = "delivered"
COLLECTION_CANCELLED = "cancelled"

VALID_COLLECTION_STATUSES = [
    COLLECTION_ASSIGNED,
    COLLECTION_ACCEPTED,
    COLLECTION_COLLECTED,
    COLLECTION_IN_TRANSIT,
    COLLECTION_DELIVERED,
    COLLECTION_CANCELLED,
]

INVOICE_UNPAID = "unpaid"
INVOICE_PAID = "paid"

RESULT_TESTING = "testing"
RESULT_PENDING_REVIEW = "pending_review"
RESULT_APPROVED = "approved"
RESULT_RELEASED = "released"
