services:
  - type: web
    name: dxcon-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: dxcon-postgres
          property: connectionString

databases:
  - name: dxcon-postgres
    databaseName: dxcon
    user: dxcon_user
