"""Reporting engine RBAC — Sprint 008."""

REPORT_READ_ROLES = frozenset({"SUPER_ADMIN", "SYSTEM_ADMIN", "ADMIN", "DOCTOR", "LAB", "RECEPTION"})
DOCTOR_APPROVE_ROLES = frozenset({"SUPER_ADMIN", "ADMIN", "DOCTOR", "LAB"})
DOCTOR_RELEASE_ROLES = frozenset({"SUPER_ADMIN", "ADMIN", "DOCTOR"})
REPORT_WRITE_ROLES = frozenset({"SUPER_ADMIN", "ADMIN", "DOCTOR", "LAB"})
PATIENT_REPORT_ROLES = frozenset({"PATIENT", "SUPER_ADMIN", "ADMIN"})

FORBIDDEN_APPROVE = frozenset({"RECEPTION", "LAB_TECHNICIAN", "PATIENT", "COLLECTOR"})
