"""Executive platform RBAC — Sprint 010."""

EXECUTIVE_READ_ROLES = frozenset({"SUPER_ADMIN", "SYSTEM_ADMIN", "ADMIN"})
EXECUTIVE_WRITE_ROLES = frozenset({"SUPER_ADMIN", "ADMIN"})
CRM_READ_ROLES = frozenset({"SUPER_ADMIN", "ADMIN", "RECEPTION"})
FINANCE_READ_ROLES = frozenset({"SUPER_ADMIN", "ADMIN", "ACCOUNTING", "RECEPTION"})
MONITORING_READ_ROLES = frozenset({"SUPER_ADMIN", "SYSTEM_ADMIN", "ADMIN"})
AUDIT_READ_ROLES = frozenset({"SUPER_ADMIN", "SYSTEM_ADMIN", "ADMIN"})
PILOT_READ_ROLES = frozenset({"SUPER_ADMIN", "ADMIN"})
