"""Patient Marketplace constants — Epic 5."""

from __future__ import annotations

PROVIDER_TYPES = (
    "LABORATORY", "CLINIC", "HOSPITAL", "DOCTOR", "IMAGING_CENTER", "HOME_COLLECTION_PROVIDER",
)
SERVICE_TYPES = (
    "LAB_TEST", "TEST_PACKAGE", "CONSULTATION", "HOME_COLLECTION", "ULTRASOUND",
    "XRAY", "IMAGING", "HEALTH_CHECK", "FOLLOW_UP",
)
LISTING_STATUSES = ("DRAFT", "PENDING_APPROVAL", "ACTIVE", "PAUSED", "REJECTED", "ARCHIVED")
BOOKING_STATUSES = (
    "DRAFT", "PRICE_CONFIRMED", "PAYMENT_PENDING", "CONFIRMED", "PROVIDER_ACCEPTED",
    "SCHEDULED", "IN_PROGRESS", "COMPLETED", "CANCELLED", "EXPIRED",
    "REFUND_PENDING", "REFUNDED",
)
PAYMENT_STATUSES = (
    "CREATED", "PENDING", "PROCESSING", "SUCCEEDED", "FAILED", "EXPIRED",
    "CANCELLED", "REFUND_PENDING", "REFUNDED", "PARTIALLY_REFUNDED",
)
PAYMENT_METHODS = (
    "QR_BANK_TRANSFER", "PAYMENT_GATEWAY", "CASH", "CARD", "CORPORATE", "INSURANCE", "WALLET_FUTURE",
)
REVIEW_STATUSES = ("PENDING", "PUBLISHED", "HIDDEN", "REJECTED")
CONSULTATION_TYPES = ("IN_PERSON", "VIDEO_FUTURE", "PHONE_FUTURE", "RESULT_REVIEW", "FOLLOW_UP")

MARKETPLACE_PERMISSIONS = (
    "MARKETPLACE_VIEW",
    "MARKETPLACE_LISTING_MANAGE",
    "MARKETPLACE_LISTING_APPROVE",
    "MARKETPLACE_PRICE_MANAGE",
    "PROMOTION_MANAGE",
    "PAYMENT_VIEW",
    "PAYMENT_RECONCILE",
)

MAX_COMPARE_ITEMS = 4
QR_EXPIRY_MINUTES = 15
MAX_BOOKING_COMPARE = 4
