SUPER_ADMIN = "SUPER_ADMIN"
ADMIN = "ADMIN"
DOCTOR = "DOCTOR"
LAB = "LAB"
COLLECTOR = "COLLECTOR"
ACCOUNTING = "ACCOUNTING"
PATIENT = "PATIENT"

ALL_ROLES = [
    SUPER_ADMIN,
    ADMIN,
    DOCTOR,
    LAB,
    COLLECTOR,
    ACCOUNTING,
    PATIENT,
]
