BOOKING_PENDING = "PENDING"
BOOKING_ASSIGNED = "ASSIGNED"
BOOKING_CHECKED_IN = "CHECKED_IN"
BOOKING_COLLECTED = "COLLECTED"

SAMPLE_IN_TRANSIT = "IN_TRANSIT"
SAMPLE_RECEIVED = "RECEIVED"
SAMPLE_PROCESSING = "PROCESSING"
SAMPLE_COMPLETED = "COMPLETED"

VALID_SAMPLE_STATUSES = [
    SAMPLE_IN_TRANSIT,
    SAMPLE_RECEIVED,
    SAMPLE_PROCESSING,
    SAMPLE_COMPLETED,
]

SHIPMENT_CREATED = "CREATED"
SHIPMENT_ACCEPTED = "ACCEPTED"
SHIPMENT_IN_TRANSIT = "IN_TRANSIT"
SHIPMENT_ARRIVED = "ARRIVED"
SHIPMENT_RECEIVED = "RECEIVED"

BOX_ONLINE = "ONLINE"
BOX_IN_USE = "IN_USE"
BOX_IN_TRANSIT = "IN_TRANSIT"
BOX_RETURNING = "RETURNING"

VALID_COLLECTOR_SHIPMENT_STATUSES = [
    SHIPMENT_CREATED,
    SHIPMENT_ACCEPTED,
    SHIPMENT_IN_TRANSIT,
]

PARTNER_PENDING = "PENDING"
PARTNER_APPROVED = "APPROVED"
PARTNER_REJECTED = "REJECTED"
PARTNER_SUSPENDED = "SUSPENDED"

PARTNER_DRAFT = "DRAFT"
PARTNER_SUBMITTED = "SUBMITTED"
PARTNER_UNDER_REVIEW = "UNDER_REVIEW"
PARTNER_ACTIVE = "ACTIVE"
PARTNER_ARCHIVED = "ARCHIVED"

VALID_PARTNER_STATUSES = [
    PARTNER_DRAFT,
    PARTNER_SUBMITTED,
    PARTNER_UNDER_REVIEW,
    PARTNER_APPROVED,
    PARTNER_ACTIVE,
    PARTNER_SUSPENDED,
    PARTNER_ARCHIVED,
    PARTNER_REJECTED,
    PARTNER_PENDING,
]

PARTNER_APPROVABLE_STATUSES = [
    PARTNER_PENDING,
    PARTNER_SUBMITTED,
    PARTNER_UNDER_REVIEW,
]

PARTNER_REJECTABLE_STATUSES = [
    PARTNER_PENDING,
    PARTNER_SUBMITTED,
    PARTNER_UNDER_REVIEW,
    PARTNER_DRAFT,
]

PARTNER_USER_ROLE_OWNER = "OWNER"
PARTNER_USER_ROLE_ADMIN = "ADMIN"
PARTNER_USER_ROLE_MANAGER = "MANAGER"
PARTNER_USER_ROLE_RECEPTION = "RECEPTION"
PARTNER_USER_ROLE_FINANCE = "FINANCE"
PARTNER_USER_ROLE_DOCTOR = "DOCTOR"
PARTNER_USER_ROLE_STAFF = "STAFF"

VALID_PARTNER_USER_ROLES = [
    PARTNER_USER_ROLE_OWNER,
    PARTNER_USER_ROLE_ADMIN,
    PARTNER_USER_ROLE_MANAGER,
    PARTNER_USER_ROLE_RECEPTION,
    PARTNER_USER_ROLE_FINANCE,
    PARTNER_USER_ROLE_DOCTOR,
    PARTNER_USER_ROLE_STAFF,
]

PARTNER_USER_ACTIVE = "ACTIVE"
PARTNER_USER_INVITED = "INVITED"
PARTNER_USER_DISABLED = "DISABLED"

VALID_PARTNER_USER_STATUSES = [
    PARTNER_USER_ACTIVE,
    PARTNER_USER_INVITED,
    PARTNER_USER_DISABLED,
]

VERIFICATION_MISSING = "MISSING"
VERIFICATION_SUBMITTED = "SUBMITTED"
VERIFICATION_VERIFIED = "VERIFIED"
VERIFICATION_REJECTED = "REJECTED"

VALID_VERIFICATION_STATUSES = [
    VERIFICATION_MISSING,
    VERIFICATION_SUBMITTED,
    VERIFICATION_VERIFIED,
    VERIFICATION_REJECTED,
]

DEFAULT_PARTNER_VERIFICATION_ITEMS = [
    "BUSINESS_LICENSE",
    "MEDICAL_LICENSE",
    "TAX_CODE",
    "BANK_ACCOUNT",
    "IDENTITY_VERIFIED",
]

CREDENTIAL_ACTIVE = "ACTIVE"
CREDENTIAL_DISABLED = "DISABLED"
CREDENTIAL_REVOKED = "REVOKED"

VALID_CREDENTIAL_STATUSES = [
    CREDENTIAL_ACTIVE,
    CREDENTIAL_DISABLED,
    CREDENTIAL_REVOKED,
]

PARTNER_TYPE_LABORATORY = "LABORATORY"
PARTNER_TYPE_CLINIC = "CLINIC"
PARTNER_TYPE_HOSPITAL = "HOSPITAL"
PARTNER_TYPE_DOCTOR = "DOCTOR"
PARTNER_TYPE_CORPORATE = "CORPORATE"
PARTNER_TYPE_HOME_CARE = "HOME_CARE"
PARTNER_TYPE_IMAGING_CENTER = "IMAGING_CENTER"

VALID_PARTNER_TYPES = [
    PARTNER_TYPE_LABORATORY,
    PARTNER_TYPE_CLINIC,
    PARTNER_TYPE_HOSPITAL,
    PARTNER_TYPE_DOCTOR,
    PARTNER_TYPE_CORPORATE,
    PARTNER_TYPE_HOME_CARE,
    PARTNER_TYPE_IMAGING_CENTER,
]

PARTNER_API_OFFLINE = "OFFLINE"
PARTNER_API_MANUAL_UPLOAD = "MANUAL_UPLOAD"
PARTNER_API_REST = "REST_API"
PARTNER_API_HL7 = "HL7"
PARTNER_API_FHIR = "FHIR"

VALID_PARTNER_API_STATUSES = [
    PARTNER_API_OFFLINE,
    PARTNER_API_MANUAL_UPLOAD,
    PARTNER_API_REST,
    PARTNER_API_HL7,
    PARTNER_API_FHIR,
]

MARKETPLACE_BOOKING_CREATED = "CREATED"
MARKETPLACE_BOOKING_CONFIRMED = "CONFIRMED"
MARKETPLACE_BOOKING_CANCELLED = "CANCELLED"
MARKETPLACE_BOOKING_ASSIGNED = "ASSIGNED"
MARKETPLACE_BOOKING_COMPLETED = "COMPLETED"

VALID_MARKETPLACE_BOOKING_STATUSES = [
    MARKETPLACE_BOOKING_CREATED,
    MARKETPLACE_BOOKING_CONFIRMED,
    MARKETPLACE_BOOKING_CANCELLED,
    MARKETPLACE_BOOKING_ASSIGNED,
    MARKETPLACE_BOOKING_COMPLETED,
]

MAPPING_ACTIVE = "ACTIVE"
MAPPING_INACTIVE = "INACTIVE"

VALID_PARTNER_SERVICE_MAPPING_STATUSES = [
    MAPPING_ACTIVE,
    MAPPING_INACTIVE,
]

MARKETPLACE_VISIBLE_PARTNER_STATUSES = [
    PARTNER_ACTIVE,
    PARTNER_APPROVED,
]

BOOKING_TIMELINE_CREATED = "CREATED"
BOOKING_TIMELINE_CONFIRMED = "CONFIRMED"
BOOKING_TIMELINE_COLLECTOR_ASSIGNED = "COLLECTOR_ASSIGNED"
BOOKING_TIMELINE_COLLECTED = "COLLECTED"
BOOKING_TIMELINE_IN_TRANSIT = "IN_TRANSIT"
BOOKING_TIMELINE_LAB_RECEIVED = "LAB_RECEIVED"
BOOKING_TIMELINE_RESULT_READY = "RESULT_READY"
BOOKING_TIMELINE_COMPLETED = "COMPLETED"
BOOKING_TIMELINE_SLOT_RESERVED = "SLOT_RESERVED"
BOOKING_TIMELINE_COLLECTOR_ASSIGNMENT_PENDING = "COLLECTOR_ASSIGNMENT_PENDING"

VALID_BOOKING_TIMELINE_EVENTS = [
    BOOKING_TIMELINE_CREATED,
    BOOKING_TIMELINE_CONFIRMED,
    BOOKING_TIMELINE_SLOT_RESERVED,
    BOOKING_TIMELINE_COLLECTOR_ASSIGNMENT_PENDING,
    BOOKING_TIMELINE_COLLECTOR_ASSIGNED,
    BOOKING_TIMELINE_COLLECTED,
    BOOKING_TIMELINE_IN_TRANSIT,
    BOOKING_TIMELINE_LAB_RECEIVED,
    BOOKING_TIMELINE_RESULT_READY,
    BOOKING_TIMELINE_COMPLETED,
]

BOOKING_EVENT_STATUS_MAP = {
    BOOKING_TIMELINE_CREATED: MARKETPLACE_BOOKING_CREATED,
    BOOKING_TIMELINE_CONFIRMED: MARKETPLACE_BOOKING_CONFIRMED,
    BOOKING_TIMELINE_COLLECTOR_ASSIGNED: MARKETPLACE_BOOKING_ASSIGNED,
    BOOKING_TIMELINE_COLLECTED: MARKETPLACE_BOOKING_ASSIGNED,
    BOOKING_TIMELINE_IN_TRANSIT: MARKETPLACE_BOOKING_ASSIGNED,
    BOOKING_TIMELINE_LAB_RECEIVED: MARKETPLACE_BOOKING_ASSIGNED,
    BOOKING_TIMELINE_RESULT_READY: MARKETPLACE_BOOKING_ASSIGNED,
    BOOKING_TIMELINE_COMPLETED: MARKETPLACE_BOOKING_COMPLETED,
}

RECOMMENDATION_TAG_DXCON_VERIFIED = "DXCON_VERIFIED"
RECOMMENDATION_TAG_FAST_RESULT = "FAST_RESULT"
RECOMMENDATION_TAG_LOW_PRICE = "LOW_PRICE"
RECOMMENDATION_TAG_HOME_COLLECTION = "HOME_COLLECTION"
RECOMMENDATION_TAG_TOP_RATED = "TOP_RATED"

RECOMMENDATION_TAG_LABELS = {
    RECOMMENDATION_TAG_DXCON_VERIFIED: "Verified partner",
    RECOMMENDATION_TAG_FAST_RESULT: "Fast result turnaround",
    RECOMMENDATION_TAG_LOW_PRICE: "Competitive price",
    RECOMMENDATION_TAG_HOME_COLLECTION: "Home collection available",
    RECOMMENDATION_TAG_TOP_RATED: "Top rated partner",
}
