BOOKING_PENDING = "PENDING"
BOOKING_ASSIGNED = "ASSIGNED"
BOOKING_CHECKED_IN = "CHECKED_IN"
BOOKING_COLLECTED = "COLLECTED"

SAMPLE_IN_TRANSIT = "IN_TRANSIT"
SAMPLE_RECEIVED = "RECEIVED"
SAMPLE_PROCESSING = "PROCESSING"
SAMPLE_COMPLETED = "COMPLETED"

VALID_SAMPLE_STATUSES = [
    SAMPLE_IN_TRANSIT,
    SAMPLE_RECEIVED,
    SAMPLE_PROCESSING,
    SAMPLE_COMPLETED,
]

SHIPMENT_CREATED = "CREATED"
SHIPMENT_ACCEPTED = "ACCEPTED"
SHIPMENT_IN_TRANSIT = "IN_TRANSIT"
SHIPMENT_ARRIVED = "ARRIVED"
SHIPMENT_RECEIVED = "RECEIVED"

BOX_ONLINE = "ONLINE"
BOX_IN_USE = "IN_USE"
BOX_IN_TRANSIT = "IN_TRANSIT"
BOX_RETURNING = "RETURNING"

VALID_COLLECTOR_SHIPMENT_STATUSES = [
    SHIPMENT_CREATED,
    SHIPMENT_ACCEPTED,
    SHIPMENT_IN_TRANSIT,
]

PARTNER_PENDING = "PENDING"
PARTNER_APPROVED = "APPROVED"
PARTNER_REJECTED = "REJECTED"
PARTNER_SUSPENDED = "SUSPENDED"

PARTNER_DRAFT = "DRAFT"
PARTNER_SUBMITTED = "SUBMITTED"
PARTNER_UNDER_REVIEW = "UNDER_REVIEW"
PARTNER_ACTIVE = "ACTIVE"
PARTNER_ARCHIVED = "ARCHIVED"

VALID_PARTNER_STATUSES = [
    PARTNER_DRAFT,
    PARTNER_SUBMITTED,
    PARTNER_UNDER_REVIEW,
    PARTNER_APPROVED,
    PARTNER_ACTIVE,
    PARTNER_SUSPENDED,
    PARTNER_ARCHIVED,
    PARTNER_REJECTED,
    PARTNER_PENDING,
]

PARTNER_APPROVABLE_STATUSES = [
    PARTNER_PENDING,
    PARTNER_SUBMITTED,
    PARTNER_UNDER_REVIEW,
]

PARTNER_REJECTABLE_STATUSES = [
    PARTNER_PENDING,
    PARTNER_SUBMITTED,
    PARTNER_UNDER_REVIEW,
    PARTNER_DRAFT,
]

PARTNER_USER_ROLE_OWNER = "OWNER"
PARTNER_USER_ROLE_ADMIN = "ADMIN"
PARTNER_USER_ROLE_MANAGER = "MANAGER"
PARTNER_USER_ROLE_RECEPTION = "RECEPTION"
PARTNER_USER_ROLE_FINANCE = "FINANCE"
PARTNER_USER_ROLE_DOCTOR = "DOCTOR"
PARTNER_USER_ROLE_STAFF = "STAFF"

VALID_PARTNER_USER_ROLES = [
    PARTNER_USER_ROLE_OWNER,
    PARTNER_USER_ROLE_ADMIN,
    PARTNER_USER_ROLE_MANAGER,
    PARTNER_USER_ROLE_RECEPTION,
    PARTNER_USER_ROLE_FINANCE,
    PARTNER_USER_ROLE_DOCTOR,
    PARTNER_USER_ROLE_STAFF,
]

PARTNER_USER_ACTIVE = "ACTIVE"
PARTNER_USER_INVITED = "INVITED"
PARTNER_USER_DISABLED = "DISABLED"

VALID_PARTNER_USER_STATUSES = [
    PARTNER_USER_ACTIVE,
    PARTNER_USER_INVITED,
    PARTNER_USER_DISABLED,
]

VERIFICATION_MISSING = "MISSING"
VERIFICATION_SUBMITTED = "SUBMITTED"
VERIFICATION_VERIFIED = "VERIFIED"
VERIFICATION_REJECTED = "REJECTED"

VALID_VERIFICATION_STATUSES = [
    VERIFICATION_MISSING,
    VERIFICATION_SUBMITTED,
    VERIFICATION_VERIFIED,
    VERIFICATION_REJECTED,
]

DEFAULT_PARTNER_VERIFICATION_ITEMS = [
    "BUSINESS_LICENSE",
    "MEDICAL_LICENSE",
    "TAX_CODE",
    "BANK_ACCOUNT",
    "IDENTITY_VERIFIED",
]

CREDENTIAL_ACTIVE = "ACTIVE"
CREDENTIAL_DISABLED = "DISABLED"
CREDENTIAL_REVOKED = "REVOKED"

VALID_CREDENTIAL_STATUSES = [
    CREDENTIAL_ACTIVE,
    CREDENTIAL_DISABLED,
    CREDENTIAL_REVOKED,
]

PARTNER_TYPE_LABORATORY = "LABORATORY"
PARTNER_TYPE_CLINIC = "CLINIC"
PARTNER_TYPE_HOSPITAL = "HOSPITAL"
PARTNER_TYPE_DOCTOR = "DOCTOR"
PARTNER_TYPE_CORPORATE = "CORPORATE"
PARTNER_TYPE_HOME_CARE = "HOME_CARE"
PARTNER_TYPE_IMAGING_CENTER = "IMAGING_CENTER"

VALID_PARTNER_TYPES = [
    PARTNER_TYPE_LABORATORY,
    PARTNER_TYPE_CLINIC,
    PARTNER_TYPE_HOSPITAL,
    PARTNER_TYPE_DOCTOR,
    PARTNER_TYPE_CORPORATE,
    PARTNER_TYPE_HOME_CARE,
    PARTNER_TYPE_IMAGING_CENTER,
]

PARTNER_API_OFFLINE = "OFFLINE"
PARTNER_API_MANUAL_UPLOAD = "MANUAL_UPLOAD"
PARTNER_API_REST = "REST_API"
PARTNER_API_HL7 = "HL7"
PARTNER_API_FHIR = "FHIR"

VALID_PARTNER_API_STATUSES = [
    PARTNER_API_OFFLINE,
    PARTNER_API_MANUAL_UPLOAD,
    PARTNER_API_REST,
    PARTNER_API_HL7,
    PARTNER_API_FHIR,
]

MARKETPLACE_BOOKING_CREATED = "CREATED"
MARKETPLACE_BOOKING_CONFIRMED = "CONFIRMED"
MARKETPLACE_BOOKING_CANCELLED = "CANCELLED"
MARKETPLACE_BOOKING_ASSIGNED = "ASSIGNED"
MARKETPLACE_BOOKING_COMPLETED = "COMPLETED"

VALID_MARKETPLACE_BOOKING_STATUSES = [
    MARKETPLACE_BOOKING_CREATED,
    MARKETPLACE_BOOKING_CONFIRMED,
    MARKETPLACE_BOOKING_CANCELLED,
    MARKETPLACE_BOOKING_ASSIGNED,
    MARKETPLACE_BOOKING_COMPLETED,
]

MAPPING_ACTIVE = "ACTIVE"
MAPPING_INACTIVE = "INACTIVE"

VALID_PARTNER_SERVICE_MAPPING_STATUSES = [
    MAPPING_ACTIVE,
    MAPPING_INACTIVE,
]

MARKETPLACE_VISIBLE_PARTNER_STATUSES = [
    PARTNER_ACTIVE,
    PARTNER_APPROVED,
]

BOOKING_TIMELINE_CREATED = "CREATED"
BOOKING_TIMELINE_CONFIRMED = "CONFIRMED"
BOOKING_TIMELINE_COLLECTOR_ASSIGNED = "COLLECTOR_ASSIGNED"
BOOKING_TIMELINE_COLLECTED = "COLLECTED"
BOOKING_TIMELINE_IN_TRANSIT = "IN_TRANSIT"
BOOKING_TIMELINE_LAB_RECEIVED = "LAB_RECEIVED"
BOOKING_TIMELINE_RESULT_READY = "RESULT_READY"
BOOKING_TIMELINE_COMPLETED = "COMPLETED"
BOOKING_TIMELINE_SLOT_RESERVED = "SLOT_RESERVED"
BOOKING_TIMELINE_COLLECTOR_ASSIGNMENT_PENDING = "COLLECTOR_ASSIGNMENT_PENDING"

VALID_BOOKING_TIMELINE_EVENTS = [
    BOOKING_TIMELINE_CREATED,
    BOOKING_TIMELINE_CONFIRMED,
    BOOKING_TIMELINE_SLOT_RESERVED,
    BOOKING_TIMELINE_COLLECTOR_ASSIGNMENT_PENDING,
    BOOKING_TIMELINE_COLLECTOR_ASSIGNED,
    BOOKING_TIMELINE_COLLECTED,
    BOOKING_TIMELINE_IN_TRANSIT,
    BOOKING_TIMELINE_LAB_RECEIVED,
    BOOKING_TIMELINE_RESULT_READY,
    BOOKING_TIMELINE_COMPLETED,
]

BOOKING_EVENT_STATUS_MAP = {
    BOOKING_TIMELINE_CREATED: MARKETPLACE_BOOKING_CREATED,
    BOOKING_TIMELINE_CONFIRMED: MARKETPLACE_BOOKING_CONFIRMED,
    BOOKING_TIMELINE_COLLECTOR_ASSIGNED: MARKETPLACE_BOOKING_ASSIGNED,
    BOOKING_TIMELINE_COLLECTED: MARKETPLACE_BOOKING_ASSIGNED,
    BOOKING_TIMELINE_IN_TRANSIT: MARKETPLACE_BOOKING_ASSIGNED,
    BOOKING_TIMELINE_LAB_RECEIVED: MARKETPLACE_BOOKING_ASSIGNED,
    BOOKING_TIMELINE_RESULT_READY: MARKETPLACE_BOOKING_ASSIGNED,
    BOOKING_TIMELINE_COMPLETED: MARKETPLACE_BOOKING_COMPLETED,
}

RECOMMENDATION_TAG_DXCON_VERIFIED = "DXCON_VERIFIED"
RECOMMENDATION_TAG_FAST_RESULT = "FAST_RESULT"
RECOMMENDATION_TAG_LOW_PRICE = "LOW_PRICE"
RECOMMENDATION_TAG_HOME_COLLECTION = "HOME_COLLECTION"
RECOMMENDATION_TAG_TOP_RATED = "TOP_RATED"

RECOMMENDATION_TAG_LABELS = {
    RECOMMENDATION_TAG_DXCON_VERIFIED: "Verified partner",
    RECOMMENDATION_TAG_FAST_RESULT: "Fast result turnaround",
    RECOMMENDATION_TAG_LOW_PRICE: "Competitive price",
    RECOMMENDATION_TAG_HOME_COLLECTION: "Home collection available",
    RECOMMENDATION_TAG_TOP_RATED: "Top rated partner",
}

CALENDAR_OWNER_PARTNER = "PARTNER"
CALENDAR_OWNER_DOCTOR = "DOCTOR"
CALENDAR_OWNER_COLLECTOR = "COLLECTOR"
CALENDAR_OWNER_LAB = "LAB"
CALENDAR_OWNER_SYSTEM = "SYSTEM"

VALID_CALENDAR_OWNER_TYPES = [
    CALENDAR_OWNER_PARTNER,
    CALENDAR_OWNER_DOCTOR,
    CALENDAR_OWNER_COLLECTOR,
    CALENDAR_OWNER_LAB,
    CALENDAR_OWNER_SYSTEM,
]

SLOT_TYPE_COLLECTION = "COLLECTION"
SLOT_TYPE_CONSULTATION = "CONSULTATION"
SLOT_TYPE_LAB_RECEIVE = "LAB_RECEIVE"
SLOT_TYPE_RESULT_REVIEW = "RESULT_REVIEW"

VALID_SLOT_TYPES = [
    SLOT_TYPE_COLLECTION,
    SLOT_TYPE_CONSULTATION,
    SLOT_TYPE_LAB_RECEIVE,
    SLOT_TYPE_RESULT_REVIEW,
]

SLOT_AVAILABLE = "AVAILABLE"
SLOT_FULL = "FULL"
SLOT_BLOCKED = "BLOCKED"
SLOT_CANCELLED = "CANCELLED"

VALID_SLOT_STATUSES = [
    SLOT_AVAILABLE,
    SLOT_FULL,
    SLOT_BLOCKED,
    SLOT_CANCELLED,
]

COLLECTOR_AVAILABLE = "AVAILABLE"
COLLECTOR_BUSY = "BUSY"
COLLECTOR_OFFLINE = "OFFLINE"

VALID_COLLECTOR_AVAILABILITY_STATUSES = [
    COLLECTOR_AVAILABLE,
    COLLECTOR_BUSY,
    COLLECTOR_OFFLINE,
]

ASSIGNMENT_PENDING = "PENDING"
ASSIGNMENT_ASSIGNED = "ASSIGNED"
ASSIGNMENT_ACCEPTED = "ACCEPTED"
ASSIGNMENT_REJECTED = "REJECTED"
ASSIGNMENT_CANCELLED = "CANCELLED"
ASSIGNMENT_COMPLETED = "COMPLETED"

VALID_ASSIGNMENT_STATUSES = [
    ASSIGNMENT_PENDING,
    ASSIGNMENT_ASSIGNED,
    ASSIGNMENT_ACCEPTED,
    ASSIGNMENT_REJECTED,
    ASSIGNMENT_CANCELLED,
    ASSIGNMENT_COMPLETED,
]

ORDER_PENDING = "PENDING"
ORDER_CONFIRMED = "CONFIRMED"
ORDER_COLLECTING = "COLLECTING"
ORDER_SAMPLE_COLLECTED = "SAMPLE_COLLECTED"
ORDER_IN_TRANSIT = "IN_TRANSIT"
ORDER_LAB_RECEIVED = "LAB_RECEIVED"
ORDER_PROCESSING = "PROCESSING"
ORDER_COMPLETED = "COMPLETED"

VALID_ORDER_LIFECYCLE_STATUSES = [
    ORDER_PENDING,
    ORDER_CONFIRMED,
    ORDER_COLLECTING,
    ORDER_SAMPLE_COLLECTED,
    ORDER_IN_TRANSIT,
    ORDER_LAB_RECEIVED,
    ORDER_PROCESSING,
    ORDER_COMPLETED,
]

COLLECTION_PENDING = "PENDING"
COLLECTION_CHECKED_IN = "CHECKED_IN"
COLLECTION_COLLECTED = "COLLECTED"
COLLECTION_IN_TRANSIT = "IN_TRANSIT"
COLLECTION_RECEIVED = "RECEIVED"

VALID_SAMPLE_COLLECTION_STATUSES = [
    COLLECTION_PENDING,
    COLLECTION_CHECKED_IN,
    COLLECTION_COLLECTED,
    COLLECTION_IN_TRANSIT,
    COLLECTION_RECEIVED,
]

SAMPLE_EVENT_CHECKED_IN = "CHECKED_IN"
SAMPLE_EVENT_COLLECTED = "COLLECTED"
SAMPLE_EVENT_IN_TRANSIT = "IN_TRANSIT"
SAMPLE_EVENT_LAB_RECEIVED = "LAB_RECEIVED"

COLLECTOR_OPS_ACTIVE = "ACTIVE"
COLLECTOR_OPS_INACTIVE = "INACTIVE"
COLLECTOR_OPS_ON_DUTY = "ON_DUTY"
COLLECTOR_OPS_OFF_DUTY = "OFF_DUTY"

VALID_COLLECTOR_OPS_STATUSES = [
    COLLECTOR_OPS_ACTIVE,
    COLLECTOR_OPS_INACTIVE,
    COLLECTOR_OPS_ON_DUTY,
    COLLECTOR_OPS_OFF_DUTY,
]

VEHICLE_ACTIVE = "ACTIVE"
VEHICLE_MAINTENANCE = "MAINTENANCE"
VEHICLE_RETIRED = "RETIRED"

VALID_COLLECTOR_VEHICLE_STATUSES = [
    VEHICLE_ACTIVE,
    VEHICLE_MAINTENANCE,
    VEHICLE_RETIRED,
]

ROUTE_PLANNED = "PLANNED"
ROUTE_OPTIMIZED = "OPTIMIZED"
ROUTE_IN_PROGRESS = "IN_PROGRESS"
ROUTE_COMPLETED = "COMPLETED"
ROUTE_CANCELLED = "CANCELLED"

VALID_COLLECTOR_ROUTE_STATUSES = [
    ROUTE_PLANNED,
    ROUTE_OPTIMIZED,
    ROUTE_IN_PROGRESS,
    ROUTE_COMPLETED,
    ROUTE_CANCELLED,
]

ROUTE_STOP_PENDING = "PENDING"
ROUTE_STOP_ARRIVED = "ARRIVED"
ROUTE_STOP_COMPLETED = "COMPLETED"
ROUTE_STOP_SKIPPED = "SKIPPED"

VALID_ROUTE_STOP_STATUSES = [
    ROUTE_STOP_PENDING,
    ROUTE_STOP_ARRIVED,
    ROUTE_STOP_COMPLETED,
    ROUTE_STOP_SKIPPED,
]

CHECK_EVENT_CHECK_IN = "CHECK_IN"
CHECK_EVENT_CHECK_OUT = "CHECK_OUT"

VALID_COLLECTOR_CHECK_EVENTS = [
    CHECK_EVENT_CHECK_IN,
    CHECK_EVENT_CHECK_OUT,
]

HANDOVER_SAMPLE = "SAMPLE"
HANDOVER_BOX = "BOX"
HANDOVER_SHIPMENT = "SHIPMENT"

VALID_HANDOVER_TYPES = [
    HANDOVER_SAMPLE,
    HANDOVER_BOX,
    HANDOVER_SHIPMENT,
]

PROOF_PHOTO = "PHOTO"
PROOF_SIGNATURE = "SIGNATURE"

VALID_PROOF_TYPES = [
    PROOF_PHOTO,
    PROOF_SIGNATURE,
]

OFFLINE_PENDING = "PENDING"
OFFLINE_SYNCED = "SYNCED"
OFFLINE_FAILED = "FAILED"

VALID_OFFLINE_SYNC_STATUSES = [
    OFFLINE_PENDING,
    OFFLINE_SYNCED,
    OFFLINE_FAILED,
]

COLLECTOR_TIMELINE_JOB_ASSIGNED = "JOB_ASSIGNED"
COLLECTOR_TIMELINE_JOB_ACCEPTED = "JOB_ACCEPTED"
COLLECTOR_TIMELINE_CHECK_IN = "CHECK_IN"
COLLECTOR_TIMELINE_CHECK_OUT = "CHECK_OUT"
COLLECTOR_TIMELINE_PICKUP = "PICKUP"
COLLECTOR_TIMELINE_QR_SCAN = "QR_SCAN"
COLLECTOR_TIMELINE_HANDOVER = "HANDOVER"
COLLECTOR_TIMELINE_GPS = "GPS"
COLLECTOR_TIMELINE_ROUTE_STARTED = "ROUTE_STARTED"
COLLECTOR_TIMELINE_ROUTE_COMPLETED = "ROUTE_COMPLETED"
COLLECTOR_TIMELINE_BOX_UPDATE = "BOX_UPDATE"
COLLECTOR_TIMELINE_PROOF = "PROOF"
COLLECTOR_TIMELINE_OFFLINE_SYNC = "OFFLINE_SYNC"

VALID_COLLECTOR_TIMELINE_EVENTS = [
    COLLECTOR_TIMELINE_JOB_ASSIGNED,
    COLLECTOR_TIMELINE_JOB_ACCEPTED,
    COLLECTOR_TIMELINE_CHECK_IN,
    COLLECTOR_TIMELINE_CHECK_OUT,
    COLLECTOR_TIMELINE_PICKUP,
    COLLECTOR_TIMELINE_QR_SCAN,
    COLLECTOR_TIMELINE_HANDOVER,
    COLLECTOR_TIMELINE_GPS,
    COLLECTOR_TIMELINE_ROUTE_STARTED,
    COLLECTOR_TIMELINE_ROUTE_COMPLETED,
    COLLECTOR_TIMELINE_BOX_UPDATE,
    COLLECTOR_TIMELINE_PROOF,
    COLLECTOR_TIMELINE_OFFLINE_SYNC,
]

MEDICAL_ORDER_BOOKED = "BOOKED"
MEDICAL_ORDER_CONFIRMED = "CONFIRMED"
MEDICAL_ORDER_PAYMENT_PENDING = "PAYMENT_PENDING"
MEDICAL_ORDER_PAID = "PAID"
MEDICAL_ORDER_COLLECTOR_ASSIGNED = "COLLECTOR_ASSIGNED"
MEDICAL_ORDER_COLLECTOR_EN_ROUTE = "COLLECTOR_EN_ROUTE"
MEDICAL_ORDER_ARRIVED = "ARRIVED"
MEDICAL_ORDER_SAMPLE_COLLECTED = "SAMPLE_COLLECTED"
MEDICAL_ORDER_IN_TRANSIT = "IN_TRANSIT"
MEDICAL_ORDER_RECEIVED_BY_LAB = "RECEIVED_BY_LAB"
MEDICAL_ORDER_PROCESSING = "PROCESSING"
MEDICAL_ORDER_VALIDATED = "VALIDATED"
MEDICAL_ORDER_REPORT_READY = "REPORT_READY"
MEDICAL_ORDER_DELIVERED = "DELIVERED"
MEDICAL_ORDER_COMPLETED = "COMPLETED"
MEDICAL_ORDER_CANCELLED = "CANCELLED"
MEDICAL_ORDER_REFUNDED = "REFUNDED"
MEDICAL_ORDER_RECOLLECT_REQUIRED = "RECOLLECT_REQUIRED"
MEDICAL_ORDER_REJECTED = "REJECTED"

VALID_MEDICAL_ORDER_STATUSES = [
    MEDICAL_ORDER_BOOKED,
    MEDICAL_ORDER_CONFIRMED,
    MEDICAL_ORDER_PAYMENT_PENDING,
    MEDICAL_ORDER_PAID,
    MEDICAL_ORDER_COLLECTOR_ASSIGNED,
    MEDICAL_ORDER_COLLECTOR_EN_ROUTE,
    MEDICAL_ORDER_ARRIVED,
    MEDICAL_ORDER_SAMPLE_COLLECTED,
    MEDICAL_ORDER_IN_TRANSIT,
    MEDICAL_ORDER_RECEIVED_BY_LAB,
    MEDICAL_ORDER_PROCESSING,
    MEDICAL_ORDER_VALIDATED,
    MEDICAL_ORDER_REPORT_READY,
    MEDICAL_ORDER_DELIVERED,
    MEDICAL_ORDER_COMPLETED,
    MEDICAL_ORDER_CANCELLED,
    MEDICAL_ORDER_REFUNDED,
    MEDICAL_ORDER_RECOLLECT_REQUIRED,
    MEDICAL_ORDER_REJECTED,
]

TERMINAL_MEDICAL_ORDER_STATUSES = [
    MEDICAL_ORDER_COMPLETED,
    MEDICAL_ORDER_CANCELLED,
    MEDICAL_ORDER_REFUNDED,
    MEDICAL_ORDER_REJECTED,
]

MEDICAL_ORDER_TRANSITIONS = {
    MEDICAL_ORDER_BOOKED: [MEDICAL_ORDER_CONFIRMED, MEDICAL_ORDER_CANCELLED],
    MEDICAL_ORDER_CONFIRMED: [MEDICAL_ORDER_PAYMENT_PENDING, MEDICAL_ORDER_CANCELLED],
    MEDICAL_ORDER_PAYMENT_PENDING: [MEDICAL_ORDER_PAID, MEDICAL_ORDER_CANCELLED],
    MEDICAL_ORDER_PAID: [
        MEDICAL_ORDER_COLLECTOR_ASSIGNED,
        MEDICAL_ORDER_CANCELLED,
        MEDICAL_ORDER_REFUNDED,
    ],
    MEDICAL_ORDER_COLLECTOR_ASSIGNED: [
        MEDICAL_ORDER_COLLECTOR_EN_ROUTE,
        MEDICAL_ORDER_CANCELLED,
        MEDICAL_ORDER_RECOLLECT_REQUIRED,
    ],
    MEDICAL_ORDER_COLLECTOR_EN_ROUTE: [
        MEDICAL_ORDER_ARRIVED,
        MEDICAL_ORDER_CANCELLED,
        MEDICAL_ORDER_RECOLLECT_REQUIRED,
    ],
    MEDICAL_ORDER_ARRIVED: [
        MEDICAL_ORDER_SAMPLE_COLLECTED,
        MEDICAL_ORDER_RECOLLECT_REQUIRED,
        MEDICAL_ORDER_CANCELLED,
    ],
    MEDICAL_ORDER_SAMPLE_COLLECTED: [
        MEDICAL_ORDER_IN_TRANSIT,
        MEDICAL_ORDER_RECOLLECT_REQUIRED,
    ],
    MEDICAL_ORDER_IN_TRANSIT: [
        MEDICAL_ORDER_RECEIVED_BY_LAB,
        MEDICAL_ORDER_RECOLLECT_REQUIRED,
    ],
    MEDICAL_ORDER_RECEIVED_BY_LAB: [
        MEDICAL_ORDER_PROCESSING,
        MEDICAL_ORDER_REJECTED,
    ],
    MEDICAL_ORDER_PROCESSING: [
        MEDICAL_ORDER_VALIDATED,
        MEDICAL_ORDER_REJECTED,
        MEDICAL_ORDER_RECOLLECT_REQUIRED,
    ],
    MEDICAL_ORDER_VALIDATED: [MEDICAL_ORDER_REPORT_READY, MEDICAL_ORDER_REJECTED],
    MEDICAL_ORDER_REPORT_READY: [MEDICAL_ORDER_DELIVERED],
    MEDICAL_ORDER_DELIVERED: [MEDICAL_ORDER_COMPLETED],
    MEDICAL_ORDER_RECOLLECT_REQUIRED: [
        MEDICAL_ORDER_COLLECTOR_ASSIGNED,
        MEDICAL_ORDER_CANCELLED,
    ],
}

MEDICAL_SAMPLE_CREATED = "CREATED"
MEDICAL_SAMPLE_COLLECTED = "COLLECTED"
MEDICAL_SAMPLE_IN_TRANSIT = "IN_TRANSIT"
MEDICAL_SAMPLE_RECEIVED = "RECEIVED"
MEDICAL_SAMPLE_PROCESSING = "PROCESSING"
MEDICAL_SAMPLE_REJECTED = "REJECTED"
MEDICAL_SAMPLE_RECOLLECT = "RECOLLECT"

VALID_MEDICAL_SAMPLE_STATUSES = [
    MEDICAL_SAMPLE_CREATED,
    MEDICAL_SAMPLE_COLLECTED,
    MEDICAL_SAMPLE_IN_TRANSIT,
    MEDICAL_SAMPLE_RECEIVED,
    MEDICAL_SAMPLE_PROCESSING,
    MEDICAL_SAMPLE_REJECTED,
    MEDICAL_SAMPLE_RECOLLECT,
]

SAMPLE_LABEL_PENDING = "PENDING"
SAMPLE_LABEL_PRINTED = "PRINTED"

VALID_SAMPLE_LABEL_STATUSES = [
    SAMPLE_LABEL_PENDING,
    SAMPLE_LABEL_PRINTED,
]

SAMPLE_INCIDENT_OPEN = "OPEN"
SAMPLE_INCIDENT_RESOLVED = "RESOLVED"

VALID_SAMPLE_INCIDENT_STATUSES = [
    SAMPLE_INCIDENT_OPEN,
    SAMPLE_INCIDENT_RESOLVED,
]

RECOLLECT_PENDING = "PENDING"
RECOLLECT_SCHEDULED = "SCHEDULED"
RECOLLECT_COMPLETED = "COMPLETED"
RECOLLECT_CANCELLED = "CANCELLED"

VALID_RECOLLECT_STATUSES = [
    RECOLLECT_PENDING,
    RECOLLECT_SCHEDULED,
    RECOLLECT_COMPLETED,
    RECOLLECT_CANCELLED,
]

BILLING_INVOICE_DRAFT = "DRAFT"
BILLING_INVOICE_ISSUED = "ISSUED"
BILLING_INVOICE_PAID = "PAID"
BILLING_INVOICE_VOID = "VOID"
BILLING_INVOICE_REFUNDED = "REFUNDED"

VALID_BILLING_INVOICE_STATUSES = [
    BILLING_INVOICE_DRAFT,
    BILLING_INVOICE_ISSUED,
    BILLING_INVOICE_PAID,
    BILLING_INVOICE_VOID,
    BILLING_INVOICE_REFUNDED,
]

BILLING_ACCOUNT_ACTIVE = "ACTIVE"
BILLING_ACCOUNT_INACTIVE = "INACTIVE"

BILLING_LEDGER_DEBIT = "DEBIT"
BILLING_LEDGER_CREDIT = "CREDIT"

TAX_RECORD_APPLIED = "APPLIED"
TAX_RECORD_VOID = "VOID"

BILLING_ADJUSTMENT_PENDING = "PENDING"
BILLING_ADJUSTMENT_APPLIED = "APPLIED"
BILLING_ADJUSTMENT_VOID = "VOID"

PAYMENT_RECORD_PENDING = "PENDING"
PAYMENT_RECORD_COMPLETED = "COMPLETED"
PAYMENT_RECORD_FAILED = "FAILED"
PAYMENT_RECORD_REFUNDED = "REFUNDED"

VALID_PAYMENT_RECORD_STATUSES = [
    PAYMENT_RECORD_PENDING,
    PAYMENT_RECORD_COMPLETED,
    PAYMENT_RECORD_FAILED,
    PAYMENT_RECORD_REFUNDED,
]

PAYMENT_GATEWAY_PENDING = "PENDING"
PAYMENT_GATEWAY_COMPLETED = "COMPLETED"
PAYMENT_GATEWAY_FAILED = "FAILED"
PAYMENT_GATEWAY_REFUNDED = "REFUNDED"

PAYMENT_PROVIDER_STRIPE = "STRIPE"
PAYMENT_PROVIDER_VNPAY = "VNPAY"
PAYMENT_PROVIDER_MOMO = "MOMO"

VALID_PAYMENT_PROVIDERS = [
    PAYMENT_PROVIDER_STRIPE,
    PAYMENT_PROVIDER_VNPAY,
    PAYMENT_PROVIDER_MOMO,
]

PAYMENT_METHOD_CARD = "CARD"
PAYMENT_METHOD_EWALLET = "EWALLET"
PAYMENT_METHOD_BANK = "BANK"

PAYMENT_REFUND_PENDING = "PENDING"
PAYMENT_REFUND_COMPLETED = "COMPLETED"
PAYMENT_REFUND_FAILED = "FAILED"

SETTLEMENT_DRAFT = "DRAFT"
SETTLEMENT_PENDING = "PENDING"
SETTLEMENT_PAID = "PAID"
SETTLEMENT_CANCELLED = "CANCELLED"

VALID_SETTLEMENT_STATUSES = [
    SETTLEMENT_DRAFT,
    SETTLEMENT_PENDING,
    SETTLEMENT_PAID,
    SETTLEMENT_CANCELLED,
]

COMMISSION_RULE_ACTIVE = "ACTIVE"
COMMISSION_RULE_INACTIVE = "INACTIVE"

REFUND_PENDING = "PENDING"
REFUND_COMPLETED = "COMPLETED"
REFUND_FAILED = "FAILED"

VALID_REFUND_STATUSES = [
    REFUND_PENDING,
    REFUND_COMPLETED,
    REFUND_FAILED,
]

PAYOUT_PENDING = "PENDING"
PAYOUT_PAID = "PAID"

DOCTOR_COMMISSION_PENDING = "PENDING"
DOCTOR_COMMISSION_PAID = "PAID"

REPORT_TYPE_KPI = "KPI"
REPORT_TYPE_REVENUE = "REVENUE"
REPORT_TYPE_OPERATIONS = "OPERATIONS"
REPORT_TYPE_PARTNERS = "PARTNERS"
REPORT_TYPE_COLLECTORS = "COLLECTORS"
REPORT_TYPE_EXECUTIVE = "EXECUTIVE"

VALID_REPORT_TYPES = [
    REPORT_TYPE_KPI,
    REPORT_TYPE_REVENUE,
    REPORT_TYPE_OPERATIONS,
    REPORT_TYPE_PARTNERS,
    REPORT_TYPE_COLLECTORS,
    REPORT_TYPE_EXECUTIVE,
]

KPI_CODE_DAILY_BOOKINGS = "DAILY_BOOKINGS"
KPI_CODE_REVENUE = "REVENUE"
KPI_CODE_ORDERS = "ORDERS"
KPI_CODE_SAMPLES = "SAMPLES"
KPI_CODE_RESULTS = "RESULTS"
KPI_CODE_SLA = "SLA"
KPI_CODE_COLLECTOR = "COLLECTOR"
KPI_CODE_PARTNER = "PARTNER"

LAB_RESULT_DRAFT = "DRAFT"
LAB_RESULT_VALIDATED = "VALIDATED"
LAB_RESULT_IN_REVIEW = "IN_REVIEW"
LAB_RESULT_APPROVED = "APPROVED"
LAB_RESULT_RELEASED = "RELEASED"
LAB_RESULT_REJECTED = "REJECTED"

VALID_LAB_RESULT_STATUSES = [
    LAB_RESULT_DRAFT,
    LAB_RESULT_VALIDATED,
    LAB_RESULT_IN_REVIEW,
    LAB_RESULT_APPROVED,
    LAB_RESULT_RELEASED,
    LAB_RESULT_REJECTED,
]

LAB_RESULT_TRANSITIONS = {
    LAB_RESULT_DRAFT: [LAB_RESULT_VALIDATED],
    LAB_RESULT_VALIDATED: [LAB_RESULT_IN_REVIEW, LAB_RESULT_REJECTED],
    LAB_RESULT_IN_REVIEW: [LAB_RESULT_APPROVED, LAB_RESULT_REJECTED],
    LAB_RESULT_APPROVED: [LAB_RESULT_RELEASED],
    LAB_RESULT_RELEASED: [],
    LAB_RESULT_REJECTED: [LAB_RESULT_DRAFT],
}

RESULT_REVIEW_PENDING = "PENDING"
RESULT_REVIEW_SUBMITTED = "SUBMITTED"
RESULT_REVIEW_APPROVED = "APPROVED"
RESULT_REVIEW_REJECTED = "REJECTED"

RESULT_SOURCE_ANALYZER = "ANALYZER"
RESULT_SOURCE_MANUAL = "MANUAL"

ATTACHMENT_TYPE_PDF = "PDF"
ATTACHMENT_TYPE_IMAGE = "IMAGE"

RESULT_TIMELINE_UPLOADED = "RESULT_UPLOADED"
RESULT_TIMELINE_VALIDATED = "RESULT_VALIDATED"
RESULT_TIMELINE_REVIEWED = "RESULT_REVIEWED"
RESULT_TIMELINE_APPROVED = "RESULT_APPROVED"
RESULT_TIMELINE_RELEASED = "RESULT_RELEASED"
RESULT_TIMELINE_REJECTED = "RESULT_REJECTED"

INTERPRETATION_RULE_ACTIVE = "ACTIVE"
INTERPRETATION_RULE_INACTIVE = "INACTIVE"
INTERPRETATION_TEMPLATE_ACTIVE = "ACTIVE"
INTERPRETATION_TEMPLATE_INACTIVE = "INACTIVE"
REFERENCE_RANGE_ACTIVE = "ACTIVE"
REFERENCE_RANGE_INACTIVE = "INACTIVE"
CRITICAL_RULE_ACTIVE = "ACTIVE"
CRITICAL_RULE_INACTIVE = "INACTIVE"

INTERPRETATION_FLAG_NORMAL = "NORMAL"
INTERPRETATION_FLAG_HIGH = "HIGH"
INTERPRETATION_FLAG_LOW = "LOW"
INTERPRETATION_FLAG_CRITICAL = "CRITICAL"

INTERPRETATION_RISK_LOW = "LOW"
INTERPRETATION_RISK_MEDIUM = "MEDIUM"
INTERPRETATION_RISK_HIGH = "HIGH"
INTERPRETATION_RISK_CRITICAL = "CRITICAL"

INTERPRETATION_LANG_EN = "en"
INTERPRETATION_LANG_VI = "vi"
VALID_INTERPRETATION_LANGUAGES = [INTERPRETATION_LANG_EN, INTERPRETATION_LANG_VI]

NOTIFICATION_STATUS_PENDING = "PENDING"
NOTIFICATION_STATUS_QUEUED = "QUEUED"
NOTIFICATION_STATUS_SENT = "SENT"
NOTIFICATION_STATUS_FAILED = "FAILED"
NOTIFICATION_STATUS_DELIVERED = "DELIVERED"

VALID_NOTIFICATION_STATUSES = [
    NOTIFICATION_STATUS_PENDING,
    NOTIFICATION_STATUS_QUEUED,
    NOTIFICATION_STATUS_SENT,
    NOTIFICATION_STATUS_FAILED,
    NOTIFICATION_STATUS_DELIVERED,
]

NOTIFICATION_CHANNEL_EMAIL = "EMAIL"
NOTIFICATION_CHANNEL_SMS = "SMS"
NOTIFICATION_CHANNEL_ZALO = "ZALO"
NOTIFICATION_CHANNEL_PUSH = "PUSH"
NOTIFICATION_CHANNEL_IN_APP = "IN_APP"

VALID_NOTIFICATION_CHANNELS = [
    NOTIFICATION_CHANNEL_EMAIL,
    NOTIFICATION_CHANNEL_SMS,
    NOTIFICATION_CHANNEL_ZALO,
    NOTIFICATION_CHANNEL_PUSH,
    NOTIFICATION_CHANNEL_IN_APP,
]

NOTIFICATION_TEMPLATE_ACTIVE = "ACTIVE"
NOTIFICATION_TEMPLATE_INACTIVE = "INACTIVE"

NOTIFICATION_DELIVERY_PENDING = "PENDING"
NOTIFICATION_DELIVERY_SENT = "SENT"
NOTIFICATION_DELIVERY_FAILED = "FAILED"
NOTIFICATION_DELIVERY_DELIVERED = "DELIVERED"

NOTIFICATION_TEMPLATE_RESULT_READY = "RESULT_READY"
NOTIFICATION_TEMPLATE_APPOINTMENT_REMINDER = "APPOINTMENT_REMINDER"
NOTIFICATION_TEMPLATE_SAMPLE_COLLECTION_REMINDER = "SAMPLE_COLLECTION_REMINDER"
NOTIFICATION_TEMPLATE_PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
NOTIFICATION_TEMPLATE_INVOICE = "INVOICE"
NOTIFICATION_TEMPLATE_CRITICAL_RESULT = "CRITICAL_RESULT"
NOTIFICATION_TEMPLATE_WELCOME = "WELCOME"
NOTIFICATION_TEMPLATE_PASSWORD_RESET = "PASSWORD_RESET"

VALID_NOTIFICATION_TEMPLATE_CODES = [
    NOTIFICATION_TEMPLATE_RESULT_READY,
    NOTIFICATION_TEMPLATE_APPOINTMENT_REMINDER,
    NOTIFICATION_TEMPLATE_SAMPLE_COLLECTION_REMINDER,
    NOTIFICATION_TEMPLATE_PAYMENT_SUCCESS,
    NOTIFICATION_TEMPLATE_INVOICE,
    NOTIFICATION_TEMPLATE_CRITICAL_RESULT,
    NOTIFICATION_TEMPLATE_WELCOME,
    NOTIFICATION_TEMPLATE_PASSWORD_RESET,
]

PATIENT_CONSENT_GRANTED = "GRANTED"
PATIENT_CONSENT_REVOKED = "REVOKED"
PATIENT_CONSENT_PENDING = "PENDING"

PATIENT_CONSENT_DATA_PROCESSING = "DATA_PROCESSING"
PATIENT_CONSENT_RESULT_SHARING = "RESULT_SHARING"
PATIENT_CONSENT_MARKETING = "MARKETING"
PATIENT_CONSENT_TELEHEALTH = "TELEHEALTH"

VALID_PATIENT_CONSENT_TYPES = [
    PATIENT_CONSENT_DATA_PROCESSING,
    PATIENT_CONSENT_RESULT_SHARING,
    PATIENT_CONSENT_MARKETING,
    PATIENT_CONSENT_TELEHEALTH,
]

PATIENT_DEVICE_MOBILE = "MOBILE"
PATIENT_DEVICE_WEB = "WEB"
PATIENT_DEVICE_TABLET = "TABLET"

DOCTOR_PROFILE_ACTIVE = "ACTIVE"
DOCTOR_PROFILE_INACTIVE = "INACTIVE"

DOCTOR_REFERRAL_PENDING = "PENDING"
DOCTOR_REFERRAL_SENT = "SENT"
DOCTOR_REFERRAL_COMPLETED = "COMPLETED"
DOCTOR_REFERRAL_CANCELLED = "CANCELLED"

DOCTOR_FOLLOWUP_PENDING = "PENDING"
DOCTOR_FOLLOWUP_REMINDED = "REMINDED"
DOCTOR_FOLLOWUP_COMPLETED = "COMPLETED"
DOCTOR_FOLLOWUP_CANCELLED = "CANCELLED"

DOCTOR_PATIENT_ACTIVE = "ACTIVE"
DOCTOR_PATIENT_INACTIVE = "INACTIVE"

CLINIC_PROFILE_ACTIVE = "ACTIVE"
CLINIC_PROFILE_INACTIVE = "INACTIVE"

CLINIC_DEPARTMENT_ACTIVE = "ACTIVE"
CLINIC_DEPARTMENT_INACTIVE = "INACTIVE"

CLINIC_DOCTOR_ACTIVE = "ACTIVE"
CLINIC_DOCTOR_INACTIVE = "INACTIVE"

CLINIC_PATIENT_ACTIVE = "ACTIVE"
CLINIC_PATIENT_INACTIVE = "INACTIVE"

CLINIC_BOOKING_PENDING = "PENDING"
CLINIC_BOOKING_CONFIRMED = "CONFIRMED"
CLINIC_BOOKING_COMPLETED = "COMPLETED"
CLINIC_BOOKING_CANCELLED = "CANCELLED"

CLINIC_ORDER_PENDING = "PENDING"
CLINIC_ORDER_PROCESSING = "PROCESSING"
CLINIC_ORDER_COMPLETED = "COMPLETED"
CLINIC_ORDER_CANCELLED = "CANCELLED"

CLINIC_REFERRAL_PENDING = "PENDING"
CLINIC_REFERRAL_SENT = "SENT"
CLINIC_REFERRAL_COMPLETED = "COMPLETED"
CLINIC_REFERRAL_CANCELLED = "CANCELLED"

INTEGRATION_PARTNER_ACTIVE = "ACTIVE"
INTEGRATION_PARTNER_INACTIVE = "INACTIVE"

INTEGRATION_CONNECTION_ACTIVE = "ACTIVE"
INTEGRATION_CONNECTION_INACTIVE = "INACTIVE"

INTEGRATION_MESSAGE_RECEIVED = "RECEIVED"
INTEGRATION_MESSAGE_PROCESSED = "PROCESSED"
INTEGRATION_MESSAGE_FAILED = "FAILED"

INTEGRATION_TYPE_LIS = "LIS"
INTEGRATION_TYPE_HIS = "HIS"

LIS_ORDER_PENDING = "PENDING"
LIS_ORDER_ACCEPTED = "ACCEPTED"
LIS_ORDER_REJECTED = "REJECTED"

LIS_RESULT_PENDING = "PENDING"
LIS_RESULT_RELEASED = "RELEASED"

HIS_PATIENT_PENDING = "PENDING"
HIS_PATIENT_SYNCED = "SYNCED"

IOT_DEVICE_ACTIVE = "ACTIVE"
IOT_DEVICE_INACTIVE = "INACTIVE"

COLD_BOX_ACTIVE = "ACTIVE"
COLD_BOX_INACTIVE = "INACTIVE"

COLD_CHAIN_ALERT_OPEN = "OPEN"
COLD_CHAIN_ALERT_RESOLVED = "RESOLVED"

COLD_CHAIN_ALERT_TEMP_HIGH = "TEMP_HIGH"
COLD_CHAIN_ALERT_TEMP_LOW = "TEMP_LOW"
COLD_CHAIN_ALERT_SHOCK = "SHOCK"
COLD_CHAIN_ALERT_BATTERY_LOW = "BATTERY_LOW"

CRM_LEAD_NEW = "NEW"
CRM_LEAD_QUALIFIED = "QUALIFIED"
CRM_LEAD_CONVERTED = "CONVERTED"
CRM_LEAD_LOST = "LOST"

CRM_PIPELINE_STAGE_LEAD = "LEAD"
CRM_PIPELINE_STAGE_QUALIFICATION = "QUALIFICATION"
CRM_PIPELINE_STAGE_MEETING = "MEETING"
CRM_PIPELINE_STAGE_QUOTATION = "QUOTATION"
CRM_PIPELINE_STAGE_NEGOTIATION = "NEGOTIATION"
CRM_PIPELINE_STAGE_WON = "WON"
CRM_PIPELINE_STAGE_LOST = "LOST"

CRM_PIPELINE_STAGES = [
    CRM_PIPELINE_STAGE_LEAD,
    CRM_PIPELINE_STAGE_QUALIFICATION,
    CRM_PIPELINE_STAGE_MEETING,
    CRM_PIPELINE_STAGE_QUOTATION,
    CRM_PIPELINE_STAGE_NEGOTIATION,
    CRM_PIPELINE_STAGE_WON,
    CRM_PIPELINE_STAGE_LOST,
]

CRM_OPPORTUNITY_OPEN = "OPEN"
CRM_OPPORTUNITY_WON = "WON"
CRM_OPPORTUNITY_LOST = "LOST"

CRM_QUOTATION_DRAFT = "DRAFT"
CRM_QUOTATION_PENDING_APPROVAL = "PENDING_APPROVAL"
CRM_QUOTATION_APPROVED = "APPROVED"
CRM_QUOTATION_REJECTED = "REJECTED"
CRM_QUOTATION_SENT = "SENT"
CRM_QUOTATION_ACCEPTED = "ACCEPTED"

CRM_APPROVAL_DRAFT = "DRAFT"
CRM_APPROVAL_PENDING = "PENDING"
CRM_APPROVAL_APPROVED = "APPROVED"
CRM_APPROVAL_REJECTED = "REJECTED"

CRM_CONTRACT_ACTIVE = "ACTIVE"
CRM_CONTRACT_EXPIRED = "EXPIRED"
CRM_CONTRACT_PENDING = "PENDING"
CRM_CONTRACT_RENEWED = "RENEWED"

CRM_CONTRACT_TYPE_PARTNER = "PARTNER"
CRM_CONTRACT_TYPE_CORPORATE = "CORPORATE"
CRM_CONTRACT_TYPE_CLINIC = "CLINIC"
CRM_CONTRACT_TYPE_HOSPITAL = "HOSPITAL"
CRM_CONTRACT_TYPE_INSURANCE = "INSURANCE"

CRM_CONTRACT_TYPES = [
    CRM_CONTRACT_TYPE_PARTNER,
    CRM_CONTRACT_TYPE_CORPORATE,
    CRM_CONTRACT_TYPE_CLINIC,
    CRM_CONTRACT_TYPE_HOSPITAL,
    CRM_CONTRACT_TYPE_INSURANCE,
]

CRM_ACTIVITY_CALL = "CALL"
CRM_ACTIVITY_MEETING = "MEETING"
CRM_ACTIVITY_EMAIL = "EMAIL"
CRM_ACTIVITY_TASK = "TASK"
CRM_ACTIVITY_NOTE = "NOTE"

CRM_PRICE_SOURCE_CATALOG = "CATALOG"
CRM_PRICE_SOURCE_CONTRACT = "CONTRACT"
CRM_PRICE_SOURCE_CUSTOMER = "CUSTOMER"

CRM_CUSTOMER_ACTIVE = "ACTIVE"
CRM_CUSTOMER_INACTIVE = "INACTIVE"

CRM_ORG_ACTIVE = "ACTIVE"
CRM_ORG_INACTIVE = "INACTIVE"

LAB_WF_BOOKING = "BOOKING"
LAB_WF_COLLECTOR_PICKUP = "COLLECTOR_PICKUP"
LAB_WF_TRANSPORT = "TRANSPORT"
LAB_WF_RECEIVED_LAB = "RECEIVED_LAB"
LAB_WF_ACCESSION = "ACCESSION"
LAB_WF_ANALYZER_QUEUE = "ANALYZER_QUEUE"
LAB_WF_ANALYZER_RUNNING = "ANALYZER_RUNNING"
LAB_WF_QC = "QC"
LAB_WF_TECHNICIAN_REVIEW = "TECHNICIAN_REVIEW"
LAB_WF_PATHOLOGIST_REVIEW = "PATHOLOGIST_REVIEW"
LAB_WF_RELEASE = "RELEASE"
LAB_WF_PATIENT_PORTAL = "PATIENT_PORTAL"

LAB_WORKFLOW_STAGES = [
    LAB_WF_BOOKING,
    LAB_WF_COLLECTOR_PICKUP,
    LAB_WF_TRANSPORT,
    LAB_WF_RECEIVED_LAB,
    LAB_WF_ACCESSION,
    LAB_WF_ANALYZER_QUEUE,
    LAB_WF_ANALYZER_RUNNING,
    LAB_WF_QC,
    LAB_WF_TECHNICIAN_REVIEW,
    LAB_WF_PATHOLOGIST_REVIEW,
    LAB_WF_RELEASE,
    LAB_WF_PATIENT_PORTAL,
]

LAB_ACCESSION_PENDING = "PENDING"
LAB_ACCESSION_IN_PROGRESS = "IN_PROGRESS"
LAB_ACCESSION_COMPLETED = "COMPLETED"
LAB_ACCESSION_REJECTED = "REJECTED"

LAB_WORKLIST_OPEN = "OPEN"
LAB_WORKLIST_IN_PROGRESS = "IN_PROGRESS"
LAB_WORKLIST_CLOSED = "CLOSED"

LAB_ANALYZER_ACTIVE = "ACTIVE"
LAB_ANALYZER_INACTIVE = "INACTIVE"
LAB_ANALYZER_MAINTENANCE = "MAINTENANCE"

LAB_QUEUE_QUEUED = "QUEUED"
LAB_QUEUE_RUNNING = "RUNNING"
LAB_QUEUE_COMPLETED = "COMPLETED"
LAB_QUEUE_FAILED = "FAILED"

LAB_QC_PENDING = "PENDING"
LAB_QC_PASSED = "PASSED"
LAB_QC_FAILED = "FAILED"

LAB_REVIEW_PENDING = "PENDING"
LAB_REVIEW_APPROVED = "APPROVED"
LAB_REVIEW_REJECTED = "REJECTED"

LAB_CRITICAL_OPEN = "OPEN"
LAB_CRITICAL_NOTIFIED = "NOTIFIED"
LAB_CRITICAL_RESOLVED = "RESOLVED"

LAB_DELTA_PENDING = "PENDING"
LAB_DELTA_ACCEPTED = "ACCEPTED"
LAB_DELTA_REJECTED = "REJECTED"

LAB_APPROVAL_PENDING = "PENDING"
LAB_APPROVAL_APPROVED = "APPROVED"
LAB_APPROVAL_REJECTED = "REJECTED"

LAB_RELEASE_PENDING = "PENDING"
LAB_RELEASE_RELEASED = "RELEASED"

LOGISTICS_DRIVER_ACTIVE = "ACTIVE"
LOGISTICS_DRIVER_INACTIVE = "INACTIVE"
LOGISTICS_DRIVER_OFF_DUTY = "OFF_DUTY"

LOGISTICS_VEHICLE_AVAILABLE = "AVAILABLE"
LOGISTICS_VEHICLE_IN_USE = "IN_USE"
LOGISTICS_VEHICLE_MAINTENANCE = "MAINTENANCE"

LOGISTICS_ROUTE_DRAFT = "DRAFT"
LOGISTICS_ROUTE_OPTIMIZED = "OPTIMIZED"
LOGISTICS_ROUTE_ACTIVE = "ACTIVE"
LOGISTICS_ROUTE_COMPLETED = "COMPLETED"

LOGISTICS_STOP_PENDING = "PENDING"
LOGISTICS_STOP_ARRIVED = "ARRIVED"
LOGISTICS_STOP_COMPLETED = "COMPLETED"
LOGISTICS_STOP_SKIPPED = "SKIPPED"

LOGISTICS_ASSIGNMENT_PENDING = "PENDING"
LOGISTICS_ASSIGNMENT_ASSIGNED = "ASSIGNED"
LOGISTICS_ASSIGNMENT_IN_PROGRESS = "IN_PROGRESS"
LOGISTICS_ASSIGNMENT_COMPLETED = "COMPLETED"
LOGISTICS_ASSIGNMENT_CANCELLED = "CANCELLED"

LOGISTICS_CUSTODY_PICKUP = "PICKUP"
LOGISTICS_CUSTODY_HANDOVER = "HANDOVER"
LOGISTICS_CUSTODY_DELIVERY = "DELIVERY"
LOGISTICS_CUSTODY_SCAN = "SCAN"
LOGISTICS_CUSTODY_EXCEPTION = "EXCEPTION"

LOGISTICS_PROOF_SIGNATURE = "SIGNATURE"
LOGISTICS_PROOF_PHOTO = "PHOTO"
LOGISTICS_PROOF_OTP = "OTP"

# Reporting & BI Platform (Release 3.5)
KPI_PERIOD_DAILY = "DAILY"
KPI_PERIOD_WEEKLY = "WEEKLY"
KPI_PERIOD_MONTHLY = "MONTHLY"
KPI_PERIOD_QUARTERLY = "QUARTERLY"
KPI_PERIOD_YEARLY = "YEARLY"

VALID_KPI_PERIODS = [
    KPI_PERIOD_DAILY,
    KPI_PERIOD_WEEKLY,
    KPI_PERIOD_MONTHLY,
    KPI_PERIOD_QUARTERLY,
    KPI_PERIOD_YEARLY,
]

KPI_CODE_TESTS = "TESTS"
KPI_CODE_COLLECTOR_UTILIZATION = "COLLECTOR_UTILIZATION"
KPI_CODE_TRANSPORT_TIME = "TRANSPORT_TIME"
KPI_CODE_TAT = "TAT"
KPI_CODE_CRITICAL_RESULTS = "CRITICAL_RESULTS"
KPI_CODE_AI_INTERPRETATION = "AI_INTERPRETATION"
KPI_CODE_DOCTOR_REVIEW_TIME = "DOCTOR_REVIEW_TIME"

REPORT_FORMAT_JSON = "JSON"
REPORT_FORMAT_PDF = "PDF"
REPORT_FORMAT_CSV = "CSV"
REPORT_FORMAT_EXCEL = "EXCEL"

VALID_REPORT_FORMATS = [
    REPORT_FORMAT_JSON,
    REPORT_FORMAT_PDF,
    REPORT_FORMAT_CSV,
    REPORT_FORMAT_EXCEL,
]

REPORT_JOB_PENDING = "PENDING"
REPORT_JOB_RUNNING = "RUNNING"
REPORT_JOB_COMPLETED = "COMPLETED"
REPORT_JOB_FAILED = "FAILED"

REPORT_SCHEDULE_DAILY = "DAILY"
REPORT_SCHEDULE_WEEKLY = "WEEKLY"
REPORT_SCHEDULE_MONTHLY = "MONTHLY"
REPORT_SCHEDULE_QUARTERLY = "QUARTERLY"
REPORT_SCHEDULE_YEARLY = "YEARLY"

VALID_REPORT_SCHEDULES = [
    REPORT_SCHEDULE_DAILY,
    REPORT_SCHEDULE_WEEKLY,
    REPORT_SCHEDULE_MONTHLY,
    REPORT_SCHEDULE_QUARTERLY,
    REPORT_SCHEDULE_YEARLY,
]

DASHBOARD_ROLE_EXECUTIVE = "EXECUTIVE"
DASHBOARD_ROLE_ADMIN = "ADMIN"
DASHBOARD_ROLE_LAB = "LAB"
DASHBOARD_ROLE_CLINIC = "CLINIC"
DASHBOARD_ROLE_PARTNER = "PARTNER"
DASHBOARD_ROLE_COLLECTOR = "COLLECTOR"

WIDGET_TYPE_REVENUE = "REVENUE"
WIDGET_TYPE_ORDERS = "ORDERS"
WIDGET_TYPE_SAMPLES = "SAMPLES"
WIDGET_TYPE_COLLECTORS = "COLLECTORS"
WIDGET_TYPE_LABORATORIES = "LABORATORIES"
WIDGET_TYPE_TOP_TESTS = "TOP_TESTS"
WIDGET_TYPE_PARTNER_REVENUE = "PARTNER_REVENUE"
WIDGET_TYPE_HEAT_MAP = "HEAT_MAP"
WIDGET_TYPE_TRANSPORT_TIMELINE = "TRANSPORT_TIMELINE"
WIDGET_TYPE_PENDING_REVIEWS = "PENDING_REVIEWS"
WIDGET_TYPE_CRITICAL_RESULTS = "CRITICAL_RESULTS"

# Multi-Lab Federation Platform (Release 3.6)
FEDERATION_LAB_ONLINE = "ONLINE"
FEDERATION_LAB_OFFLINE = "OFFLINE"
FEDERATION_LAB_CONNECTED = "CONNECTED"
FEDERATION_LAB_DISCONNECTED = "DISCONNECTED"
FEDERATION_PROVIDER_ACTIVE = "ACTIVE"
FEDERATION_PROVIDER_INACTIVE = "INACTIVE"

FAILOVER_TRIGGER_LAB_OFFLINE = "LAB_OFFLINE"
FAILOVER_TRIGGER_ANALYZER_DOWN = "ANALYZER_DOWN"
FAILOVER_TRIGGER_QC_FAILED = "QC_FAILED"
FAILOVER_TRIGGER_HOLIDAY = "HOLIDAY_CLOSED"
FAILOVER_TRIGGER_OVER_CAPACITY = "OVER_CAPACITY"
FAILOVER_TRIGGER_SLA_TIMEOUT = "SLA_TIMEOUT"

# AI Clinical Decision Support (Release 3.7)
CDS_PANEL_CBC = "CBC"
CDS_PANEL_CHEMISTRY = "CHEMISTRY"
CDS_PANEL_LIVER = "LIVER"
CDS_PANEL_KIDNEY = "KIDNEY"
CDS_PANEL_LIPID = "LIPID"
CDS_PANEL_HBA1C = "HBA1C"
CDS_PANEL_THYROID = "THYROID"
CDS_PANEL_URINALYSIS = "URINALYSIS"
CDS_PANEL_COAGULATION = "COAGULATION"

CRITICAL_ALERT_PANIC = "PANIC_VALUE"
CRITICAL_ALERT_DELTA = "DELTA_CHECK"
CRITICAL_ALERT_CORRELATION = "MULTI_MARKER"
CRITICAL_ALERT_REPEATED = "REPEATED_ABNORMALITY"

# Medical Knowledge & Guideline Engine (Release 3.8)
GUIDELINE_PACK_WHO = "WHO"
GUIDELINE_PACK_CLSI = "CLSI"
GUIDELINE_PACK_IFCC = "IFCC"
GUIDELINE_PACK_CAP = "CAP"
GUIDELINE_PACK_CDC = "CDC"
GUIDELINE_PACK_VN_MOH = "VN_MOH"

EVIDENCE_LEVEL_A = "A"
EVIDENCE_LEVEL_B = "B"
EVIDENCE_LEVEL_C = "C"
EVIDENCE_LEVEL_D = "D"

KNOWLEDGE_STATUS_ACTIVE = "ACTIVE"
KNOWLEDGE_STATUS_ARCHIVED = "ARCHIVED"
